name = "CEnum"
uuid = "fa961155-64e5-5f13-b03f-caf6b980ea82"
authors = ["SimonDanisch <sdanisch@gmail.com>", "Gnimuc <qiyupei@gmail.com>"]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
